name: PR Linting

on: [pull_request]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    environment: dev
    strategy:
      matrix:
        node: ['14']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn lint
      - name: Cancelling workflow due to error
        if: ${{ failure() }}
        uses: andymckay/cancel-action@0.2
